

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
     - .env
    restart: always
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - .env
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oait-si-/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oait-si-/data/wordpress
